# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Advanced Custom Gutenberg Blocks
email: mariyan_dimitrov@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Tutorials about how to customise our custom Gutenberg blocks on advanced level.
destination: docs
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: ""
github_username:  mariyan-dimitrov

# Build settings
markdown: kramdown